// flow-typed signature: 407f90b828d7c4f24598661472fadbdf
// flow-typed version: <<STUB>>/typeface-roboto_v0.0.43/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typeface-roboto'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typeface-roboto' {
  declare module.exports: any;
}
